### ISSUE TITLE
Bug: Restoring a machine version in the Simulate tab crashes the Studio

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#159]
### Description

If you have two versions of a machine, with different events and states, restoring a version while on the Simulate tab will crash the page after restoring. This is probably caused because the simulation can't find the current state on the restored version.

### Expected result

Simulation should reset, or maybe restoring versions shouldn't be possible in the Simulate tab.

### Actual result

Page crashes with a "Looks like you've ended up in an invalid state. Refresh the page to retry." error.

### Which browsers are you seeing the problem on?

Chrome

### Additional details

https://user-images.githubusercontent.com/12085950/232080256-8ba79482-981d-4ea3-8ac1-df875d49a496.mp4

#### Stack trace:

```
_app-aa70bc3719c3c07f.js:11 TypeError: Cannot read properties of undefined (reading 'uniqueId')
    at 646-ee468287a60aa246.js:1:42511
    at Array.map (<anonymous>)
    at 646-ee468287a60aa246.js:1:42467
    at Array.flatMap (<anonymous>)
    at 646-ee468287a60aa246.js:1:42348
    at t (_app-aa70bc3719c3c07f.js:31:416)
    at _app-aa70bc3719c3c07f.js:31:621
    at Object.aP [as useSyncExternalStore] (framework-d6b15d8b3dd1dcdb.js:9:63048)
    at n.useSyncExternalStore (framework-d6b15d8b3dd1dcdb.js:25:6223)
    at e.useSyncExternalStoreWithSelector (_app-aa70bc3719c3c07f.js:31:690)
    at h (_app-aa70bc3719c3c07f.js:15:46945)
    at 646-ee468287a60aa246.js:1:42113
    at ab (framework-d6b15d8b3dd1dcdb.js:9:60916)
    at ud (framework-d6b15d8b3dd1dcdb.js:9:72802)
    at us (framework-d6b15d8b3dd1dcdb.js:9:72008)
    at i (framework-d6b15d8b3dd1dcdb.js:9:122856)
    at oO (framework-d6b15d8b3dd1dcdb.js:9:99113)
    at framework-d6b15d8b3dd1dcdb.js:9:98980
    at oF (framework-d6b15d8b3dd1dcdb.js:9:98987)
    at ox (framework-d6b15d8b3dd1dcdb.js:9:95739)
    at oC (framework-d6b15d8b3dd1dcdb.js:9:96128)
    at r4 (framework-d6b15d8b3dd1dcdb.js:9:44777)
    at framework-d6b15d8b3dd1dcdb.js:9:93631
```

Which points to this line in https://stately.ai/registry/_next/static/chunks/646-ee468287a60aa246.js.

```js
return n.map(e=>a.snapshot.getNodeBySerialisableId(e).uniqueId)
```

**Comment by kevinmaes** [comment]
@Valkendorm Thanks for reporting this. We are about to release improvements to how restoration works which should keep the machine contents while in Simulation mode in sync with any version and also switching between versions. But we will also disable restoration while in Simulation mode since it's not really expected.

**Comment by kevinmaes** [comment]
@Valkendorm The fix for this has just been released! Thanks again for the feedback!
